services:
  - type: web
    name: maple-and-moss-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && flask db upgrade
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT "app:create_app()"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0